# Generated by Django 2.2.4 on 2019-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.CharField(max_length=32)),
                ('caseName', models.TextField()),
                ('rebateAmount', models.CharField(max_length=64)),
                ('assertResult', models.BooleanField()),
                ('executionTime', models.DateTimeField(auto_now_add=True)),
                ('CaseExecutionResult', models.TextField(null=True)),
                ('unusualStepResult', models.TextField(blank=True, null=True)),
                ('guid', models.CharField(blank=True, max_length=64, null=True)),
                ('executionUser', models.CharField(blank=True, max_length=24, null=True)),
                ('project', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.CharField(max_length=32)),
                ('functionPoint', models.CharField(max_length=32, null=True)),
                ('caseName', models.TextField()),
                ('softId', models.CharField(max_length=32, null=True)),
                ('softPoint', models.CharField(max_length=16, null=True)),
                ('softMoney', models.CharField(max_length=16, null=True)),
                ('softCash', models.CharField(max_length=16, null=True)),
                ('isSupply', models.CharField(max_length=16, null=True)),
                ('pointDownloadNumber', models.CharField(max_length=16)),
                ('wxtDownloadNumber', models.CharField(max_length=16)),
                ('scanCodeDownloadNumber', models.CharField(max_length=16)),
                ('rebateAmount', models.CharField(max_length=64)),
                ('addTime', models.DateTimeField()),
                ('softAuthorId', models.CharField(max_length=32, null=True)),
                ('downloadAuthorId', models.CharField(max_length=32, null=True)),
                ('createTime', models.DateTimeField()),
                ('caseNote', models.TextField(null=True)),
                ('ifLevel', models.CharField(blank=True, max_length=12, null=True)),
                ('newCaseUser', models.CharField(blank=True, max_length=24, null=True)),
                ('project', models.CharField(max_length=64, null=True)),
                ('downloadAuthorTypeName', models.CharField(max_length=32, null=True)),
                ('backCashRate', models.CharField(max_length=16, null=True)),
                ('backMoneyRate', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSoftId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softId', models.IntegerField()),
                ('guid', models.CharField(blank=True, max_length=128, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
