# Generated by Django 2.2.4 on 2019-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20190926_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='routeType',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
