# Generated by Django 2.2.4 on 2019-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20190919_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
