# Generated by Django 2.2.4 on 2019-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_usersoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regTime',
            field=models.DateTimeField(null=True),
        ),
    ]
