# Generated by Django 2.2.4 on 2019-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_user_regtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userState',
            field=models.BooleanField(null=True),
        ),
    ]
